resolver: lts-6.1
flags: {}
extra-deps:
- peggy-0.3.2
packages:
- location:
    git: https://github.com/TokTok/hs-msgpack.git
    commit: d4abb4a320250047f512f2b3860fa051f9b530ac
  extra-dep: true
- msgpack-rpc/
# - msgpack-aeson/
nix:
    enable: false
    packages: [zlib]
# - msgpack-idl/
# - msgpack-idl-web/
